from .bedwars import *
from .buildbuttle import *
from .skyblock_player import *
from .skyblock import *
from .skywars import *
from .murdermystery import *
from .duels import *
from .tntgames import *
from .UHC import *
